#! /bin/bash
clear
echo `tput setaf 111`"
███╗   ███╗██╗   ██╗     ███████╗ ██████╗ █████╗ ███╗   ██╗███╗   ██╗███████╗██████╗ 
████╗ ████║╚██╗ ██╔╝     ██╔════╝██╔════╝██╔══██╗████╗  ██║████╗  ██║██╔════╝██╔══██╗
██╔████╔██║ ╚████╔╝█████╗███████╗██║     ███████║██╔██╗ ██║██╔██╗ ██║█████╗  ██████╔╝
██║╚██╔╝██║  ╚██╔╝ ╚════╝╚════██║██║     ██╔══██║██║╚██╗██║██║╚██╗██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║   ██║         ███████║╚██████╗██║  ██║██║ ╚████║██║ ╚████║███████╗██║  ██║
╚═╝     ╚═╝   ╚═╝         ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝

          ________________________________________________________________________
         |                                                                        
         |     	               WebSite: Ayoubamg.com                           
         |	               Creator: Ayoub Amengay		          
         | 	               E-mail: Ayoub.konan6@gmil.com		                   							     	         
         |
         --------------------------------------------------------------------------

"
sleep .12
echo `tput setaf 209` ' My scanner is Very Powerful and Easy Automated Web Penetration Testing Tool'
echo '    My scanner uses whois,whatweb,subfinder,wafw00f,a2sv,dnsenum,'
echo '    sqlmap,wpscan,goofile,ffuf,photon,hakrawler For Scan'
echo '     Working with My scanner is easier than you think'
echo '      In a word: My scanner is Very good and Easy Scanner'
echo '        WebSite: Ayoubamg.com'
echo '         E-mail: Ayoub.konan6@gmail.com'
echo `tput setaf 2` '' `tput sgr0`
